version: '3.4'

services:
  storeservices.api.author:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "6104:8080"

  storeservices.api.book:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "6105:8080"


  storeservices.api.shoppingcart:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Services__Authors=http://storeservices.api.author:8080
      - Services__Books=http://storeservices.api.book:8080
    ports:
    ports:
      - "6106:8080"

