// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreServices.Api.ShoppingCart.Persistence;

#nullable disable

namespace StoreServices.Api.ShoppingCart.Migrations
{
    [DbContext(typeof(ShoppingCartContext))]
    [Migration("20240106235900_MySQLInitialMigration")]
    partial class MySQLInitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StoreServices.Api.ShoppingCart.Models.ShoppingCartSession", b =>
                {
                    b.Property<int>("ShoppingCartSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ShoppingCartSessionId");

                    b.ToTable("ShoppingCartSession");
                });

            modelBuilder.Entity("StoreServices.Api.ShoppingCart.Models.ShoppingCartSessionDetail", b =>
                {
                    b.Property<int>("ShoppingCartSessionDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SelectedProduct")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ShoppingCartSessionId")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartSessionDetailId");

                    b.HasIndex("ShoppingCartSessionId");

                    b.ToTable("ShoppingCartSessionDetail");
                });

            modelBuilder.Entity("StoreServices.Api.ShoppingCart.Models.ShoppingCartSessionDetail", b =>
                {
                    b.HasOne("StoreServices.Api.ShoppingCart.Models.ShoppingCartSession", "ShoppingCartSession")
                        .WithMany("ShoppingCartSessionDetails")
                        .HasForeignKey("ShoppingCartSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingCartSession");
                });

            modelBuilder.Entity("StoreServices.Api.ShoppingCart.Models.ShoppingCartSession", b =>
                {
                    b.Navigation("ShoppingCartSessionDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
